name: StopWhiners
main: com.andor.stopwhiners.StopWhinersPlugin
version: 1

commands:
    giveback:
        description: Give back items lost upon death to players. Accepts more than one name.
        usage: /giveback [list of players]
    getback:
        description: Get back your items lost upon death. 
        usage: /getback
        
permissions:
    stopwhiners.*:
        description: Gives access to item returning commands
        children:
            stopwhiners.giveback: false
            stopwhiners.getback: false
    stopwhiners.giveback:
        description: Gives back the items lost on the last death to user
        default: op
    stopwhiners.getback:
        description: Gets your items back lost on the last death
        default: op
    stopwhiners.auto:
        description: Automatically restores your items after respawning
        default: false