name: StopWhiners
main: com.andor.stopwhiners.StopWhinersPlugin
version: 1

commands:
    giveback:
        description: Give back items lost upon death to players. Accepts more than one name.
        usage: /giveback [list of players]